<?php
echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
echo $this->doctype();
?>
<html>
<head>
<?php
echo $this->headTitle()?>
<?php

echo $this->headMeta()?>
<?php

echo $this->headLink()?>
<?php

echo $this->headStyle()?>
<?php

echo $this->headScript()?>
<?php

echo $this->inlineScript()?>
<base href="<?php
echo App::baseUri()?>" />
</head>
<body>
<div class="top_bg">
<div class="container_16">
<div class="grid_5">
<div class="colortheme"></div>
<a href="default.htm"><img src="<?php
echo $this->tplIMG?>logo.png"
	class="logo" alt="Memix" /></a></div>

<div class="grid_11 menu"><!-- Top menu Start -->    
<?php
echo $this->partial('top_menu.phtml')?>
      <!-- Top menu End --></div>
</div>
</div>
<div class="clear">&nbsp;</div>
<?php
echo $this->partial('subpageheader.phtml')?>
<div class="clear">&nbsp;</div>
<div class="clear">&nbsp;</div>
<div class="content cbg">
<div class="container_16 linebg"><!--Left part of text follows here-->
    <?php
    echo $this->partial('left_part_content.phtml')?>
    <!--End of the Left part text  --> <!--Right part of text follows here-->
	  <?php
echo $this->partial('right_part.phtml')?>
      <!--End of the Right part text  --></div>
</div>
</div>
<div class="clear">&nbsp;</div>
<!-- Footer Block Start -->
 <?php
echo $this->partial('page_footer.phtml')?>
<!-- Footer Block End -->
</body>
</html>