   <div class="grid_11 para sepline">
      <div class="text">
        <h2>Welcome to <span>memex!</span></h2>
        <p>The font i have used in this website is an Arial system default font with letter-spacing -1px. In vel orci. Praesent sit amet diam sed orci volutpat facilisis. Aenean varius, ligula a blandit ornare, nulla elit porttitor tellus, quis bibendum elit ante nec metus. Donec metus lacus, porta id, auctor sit amet, aliquam eu, lacus. Quisque sagittis vulputate orci. </p>
        <p>In vel orci. Praesent sit amet diam sed orci volutpat facilisis. Aenean varius, ligula a blandit ornare, nulla elit porttitor tellus, quis bibendum elit ante nec metus. Donec metus lacus, porta id, auctor sit amet, aliquam eu, lacus. Quisque sagittis vulputate orci.In vel orci. Praesent sit amet diam sed orci volutpat facilisis. Aenean varius, ligula a blandit ornare, nulla elit porttitor tellus, quis bibendum elit ante nec metus. Donec metus lacus, porta id, auctor sit amet, aliquam eu, lacus. Quisque sagittis vulputate orci.</p>
        <br />
        <h2>Featured Products</h2>
        <div class="servicebox"> <img src="wp-content/uploads/2009/05/futuron_15.jpg"alt='Featured Prudct3' class="leftalign" />
          <div class="rightpara2">
            <p>This is the placeholder for your services details list and you can place some of the content related to your services and have some list items placed in it in the unordered list style of some ordered list style and you can describe the long text here by adding more images in it and have some extra stuff.</p>
          </div>
        </div>
        <div class="servicebox"> <img src="wp-content/uploads/2009/05/bplanet_15.jpg"alt='Featured Product2' class="leftalign" />
          <div class="rightpara2">
            <p>This is the placeholder for your services details list and you can place some of the content related to your services and have some list items placed in it in the unordered list style of some ordered list style and you can describe the long text here by adding more images in it and have some extra stuff.</p>
          </div>
        </div>
        <div class="servicebox"> <img src="wp-content/uploads/2009/05/pro2_15.jpg"alt='Future Product1' class="leftalign" />
          <div class="rightpara2">
            <p>This is the placeholder for your services details list and you can place some of the content related to your services and have some list items placed in it in the unordered list style of some ordered list style and you can describe the long text here by adding more images in it and have some extra stuff</p>
          </div>
        </div>
      </div>
    </div>