<div class="grid_11 para sepline">
                  <div class="text">
								
							
                              	<div class="blogbox bordersub"> 

	
<a  href="@p=45"><img src="wp-content/themes/memex/timthumb.php@src=http_3A_2F_2Fwpdemo.bannersmonster.com_2Fmemex_2Fwp-content_2Fuploads_2F2009_2F05_2Ffullimg.jpg&w=220&h=220" alt="Sed venenatis erat non ipsum"  class="borderimg leftalign" /></a>
                              <h2><a  href="@p=45">Sed venenatis erat non ipsum</a></h2>
                              <span class="postinfo">Wednesday, May 20th, 2009 <a href="@cat=5" title="View all posts in Category1" rel="category">Category1</a>,  <a href="@cat=6" title="View all posts in Category2" rel="category">Category2</a>,  <a href="@cat=7" title="View all posts in Category3" rel="category">Category3</a> by  admin </span><br />
                              	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at varius elit. Quisque interdum porta leo ac sodales. Sed venenatis erat non ipsum tempus elementum. Cras sit amet consequat massa. Vestibulum vestibulum dignissim auctor. In hac habitasse platea dictumst. Vivamus erat lectus, ornare quis viverra sodales, lacinia eu odio. Phasellus elementum, urna sed luctus dictum, orci ligula scelerisque orci, quis rutrum metus lectus et est. Quisque vulputate arcu at quam faucibus lobortis. Donec arcu diam, bibendum at condimentum quis, bibendum et turpis</p>
                        </div>
                        <div class="bottomblog"><a  href="@p=45"  rel="bookmark" title="Permanent Link to Sed venenatis erat non ipsum" class="button rightalign">continue reading</a><a href="@p=45#comments" class="button leftalign"  title="Comment on Sed venenatis erat non ipsum"> Comments 1</a></div>
                        <br />
						

	  
		<div class="blogbox bordersub"> 

	
<a  href="@p=31"><img src="wp-content/themes/memex/timthumb.php@src=http_3A_2F_2Fwpdemo.bannersmonster.com_2Fmemex_2Fwp-content_2Fuploads_2F2009_2F05_2Fconspicuous.jpg&w=220&h=220" alt="Conspicuous Vestibulum ante ipsum primis in faucibus"  class="borderimg leftalign" /></a>
                              <h2><a  href="@p=31">Conspicuous Vestibulum ante ipsum primis in faucibus</a></h2>
                              <span class="postinfo">Tuesday, May 19th, 2009 <a href="@cat=4" title="View all posts in Blog" rel="category">Blog</a> by  admin </span><br />
                              	<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis condimentum condimentum justo. Proin non libero. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce nec diam non turpis laoreet fringilla. Nulla dapibus, neque vel sollicitudin lacinia.</p>
                        </div>
                        <div class="bottomblog"><a  href="@p=31"  rel="bookmark" title="Permanent Link to Conspicuous Vestibulum ante ipsum primis in faucibus" class="button rightalign">continue reading</a><a href="@p=31#respond" class="button leftalign"  title="Comment on Conspicuous Vestibulum ante ipsum primis in faucibus">Comments 0</a></div>
                        <br />
						

	  
		<div class="blogbox bordersub"> 

	
<a  href="@p=29"><img src="wp-content/themes/memex/timthumb.php@src=http_3A_2F_2Fwpdemo.bannersmonster.com_2Fmemex_2Fwp-content_2Fuploads_2F2009_2F05_2Fbrightfull.jpg&w=220&h=220" alt="Lorem IpsumCras dictumlacinia"  class="borderimg leftalign" /></a>
                              <h2><a  href="@p=29">Lorem IpsumCras dictumlacinia</a></h2>
                              <span class="postinfo">Tuesday, May 19th, 2009 <a href="@cat=4" title="View all posts in Blog" rel="category">Blog</a> by  admin </span><br />
                              	<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis condimentum condimentum justo. Proin non libero. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce nec diam non turpis laoreet fringilla. Nulla dapibus, neque vel sollicitudin lacinia.</p>
                        </div>
                        <div class="bottomblog"><a  href="@p=29"  rel="bookmark" title="Permanent Link to Lorem IpsumCras dictumlacinia" class="button rightalign">continue reading</a><a href="@p=29#comments" class="button leftalign"  title="Comment on Lorem IpsumCras dictumlacinia">2 Comments</a></div>
                        <br />
						

	  
		<div class="blogbox bordersub"> 

	
<a  href="@p=27"><img src="wp-content/themes/memex/timthumb.php@src=http_3A_2F_2Fwpdemo.bannersmonster.com_2Fmemex_2Fwp-content_2Fuploads_2F2009_2F05_2Ffullimg.jpg&w=220&h=220" alt="Lorem IpsumCras dictumlacinia"  class="borderimg leftalign" /></a>
                              <h2><a  href="@p=27">Lorem IpsumCras dictumlacinia</a></h2>
                              <span class="postinfo">Tuesday, May 19th, 2009 <a href="@cat=4" title="View all posts in Blog" rel="category">Blog</a> by  admin </span><br />
                              	<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis condimentum condimentum justo. Proin non libero. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce nec diam non turpis laoreet fringilla. Nulla dapibus, neque vel sollicitudin lacinia.</p>
                        </div>
                        <div class="bottomblog"><a  href="@p=27"  rel="bookmark" title="Permanent Link to Lorem IpsumCras dictumlacinia" class="button rightalign">continue reading</a><a href="@p=27#respond" class="button leftalign"  title="Comment on Lorem IpsumCras dictumlacinia">Comments 0</a></div>
                        <br />
						

	  
		<div class="navigation">
			<span class="leftalign"></span>
			<span class="rightalign"></span>
		</div>
	

                    <!-- Pagination -->
 </div>
            </div>