<?php
echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
echo $this->doctype();
?>
<html>
<head>
<?php echo $this->headTitle()?>

<?php echo $this->headMeta()?>

<?php echo $this->headLink()?>

<?php echo $this->headStyle()?>

<!--[if IE 6]>
<link rel="stylesheet" type="text/css" href="<?php echo $this->tplCSS?>style-ie.css" />
<![endif]-->

<?php echo $this->headScript()?>

<?php echo $this->inlineScript()?>

<base href="<?php echo App::baseUri()?>" />
</head>
<body>
<div id="wrapper">
  <div id="wrapper-in">
    <div id="header">
      <div id="header-content">
        <div id="top-search-wrap"> <a id="feed" href="/">Subscribe to RSS2</a>
          <form id="top-search" action="/" method="get">
            <input type="submit" id="top-search-submit" value="" class="input-submit"/>
            <input type="text" id="top-s" name="s" value="" class="input-text"/>
          </form>
        </div>
        <div id="branding"> <span id="blog-title"><a href="/" title="Test blog" rel="home">Test blog</a></span>
          <h1 id="blog-description"><span>Yet another blog </span></h1>
        </div>
        <!-- /branding -->
        <div class="clear"></div>
      </div>
      <!-- /header-content -->
      <div id="header-bottom">
        <div id="cat-menu" class="menu">
          <ul id="cat-menu-shadow">
            <li class="cat-item cat-item-1"><a href="/" title="View all posts in category &laquo;Default category&raquo;">Default category</a> </li>
          </ul>
          <ul>
            <li class="cat-item cat-item-1"><a href="/" title="View all posts in category &laquo;Default category&raquo;">Default category</a> </li>
          </ul>
        </div>
        <div class="clear"></div>
      </div>
      <!-- /header-bottom -->
    </div>
    <!-- /header -->
    <div id="container">
      <div id="top-container">
        <div class="clear"></div>
      </div>
      <!-- /top-container -->
      <div id="content">
         <?php echo $this->layout()->content ?>

         <div class="navigation">
          <div class="alignleft"></div>
          <div class="alignright"></div>
        </div>
      </div>
      <!-- /content -->
      <div id="sidebar">
        <ul>
          <li id="recent-comments-3" class="widget">
            <div class="widget-top">
              <h4 class="widget-title">Comments</h4>
              <div class="widget-content">
                <ul id="recentcomments">
                  <li class="recentcomments">admin <a href="/">Hello, world!</a></li>
                  <li class="recentcomments"><a href='/' rel='external nofollow' class='url'>admin</a> on <a href="/">Hello, world!</a></li>
                </ul>
              </div>
            </div>
            <div class="widget-bottom"></div>
          </li>
        </ul>
      </div>
      <!-- /sidebar -->
      <div class="clear"></div>
    </div>
  </div>
</div>
<div id="footer">
  <div id="footer-in"> <span id="footer-text"> Copyright &copy; 2009 Test blog &ndash; Yet another blog</span>
    <div class="clear"></div>
  </div>
</div>
</body>
</html>