<h3><?php echo __('Manage blogs')?></h3>
<p><a href="<?php
echo $this->url(array('action' => 'new-blog'))?>"><?php
echo __('Create new blog')?></a></p>

<?php if (count($this->blogsDataGrid) > 0): ?>
<table class="grid">
	<thead>
		<th><?php echo $this->paginationSort('ID', 'id')?></th>
		<th><?php echo $this->paginationSort('Title', 'title')?></th>
		<th><?php echo $this->paginationSort('Created', 'created')?></th>
		<th><?php echo $this->paginationSort('Type')?></th>
		<th><?php echo __('Actions')?></th>
	</thead>
	<tbody>
<?php
    foreach($this->blogsDataGrid as $blog) { ?>
	<tr class="<?php
    echo $this->cycle(array("odd" , "even"))->next()?>">
			<td><?php
    echo $blog->id?></td>
			<td><?php
    echo $blog->title?></td>
			<td><?php
    echo date("Y-t-d", strtotime($blog->created))?></td>
			<td><?php
    echo $this->types[$blog->type]?></td>
			<td><a
				href="<?=$this->url(array('action' => 'edit-blog' , 'id' => $blog->id, 'page' => null))?>"><?=__('Edit')?></a>
			<a
				href="<?=$this->url(array('action' => 'delete-blog' , 'id' => $blog->id, 'page' => null))?>"><?=__('Delete')?></a>
			</td>
		</tr>
<?php
}

?>
  </tbody>
</table>

<p><?php echo $this->paginationControl($this->blogsDataGrid)?></p>

<?php else: ?>
<p><?php echo __('No blogs here')?></p>
<?php endif;