<?php
echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
echo $this->doctype();

?>
<html>
<head>
<?php
echo $this->headTitle()?>
<?php echo $this->headMeta()?>

<?php echo $this->headLink()?>

<?php echo $this->headStyle()?>

<?php echo $this->headScript()?>
<link href="/static/system/backoffice/css/style.css" rel="stylesheet" media="all" />
<script type="text/javascript" src="/static/system/clientscripts/superfish.js"></script>
<script type="text/javascript" src="/static/system/clientscripts/tooltip.js"></script>
<script type="text/javascript" src="/static/system/clientscripts/tablesorter.js"></script>
<script type="text/javascript" src="/static/system/clientscripts/tablesorter-pager.js"></script>
<script type="text/javascript" src="/static/system/clientscripts/cookie.js"></script>
<script type="text/javascript" src="/static/system/clientscripts/custom.js"></script>
<!--[if IE 6]>
	<link href="css/ie6.css" rel="stylesheet" media="all" />	
	<![endif]-->
<!--[if IE 7]>
	<link href="css/ie7.css" rel="stylesheet" media="all" />
	<![endif]-->
<?php echo $this->inlineScript()?>
</head>
<body>
<div id="header">
  <div id="top-menu"> <a href="#" title="My account">My account</a> | <a href="#" title="Settings">Settings</a> | <a href="#" title="Contact us">Contact us</a> <span>Logged in as <a href="#" title="Logged in as admin">admin</a></span> | <a href="#" title="Edit profile">Edit profile</a> | <a href="#" title="Logout">Logout</a> </div>
  <div id="sitename"> <a href="index.html" class="logo float-left" title="Admintasia">Admintasia</a>
    <div class="button float-right"> <a href="#" id="dialog_link" class="btn ui-state-default ui-corner-all"><span class="ui-icon ui-icon-newwin"></span>Open Dialog</a> <a href="#" id="login_dialog" class="btn ui-state-default ui-corner-all"><span class="ui-icon ui-icon-image"></span>Open Login Box</a> </div>
  </div>
  <ul id="navigation" class="sf-navbar">
    <li> <a href="index.html">Dashboard</a></li>
    <li> <a href="#">Dummy menu</a>
      <ul>
        <li> <a href="#">Menu item 1</a>
          <ul>
            <li><a href="#">Subitem 1</a></li>
            <li><a href="#">Subitem 2</a></li>
          </ul>
        </li>
      </ul>
    </li>
    <li> <a href="#">Layout Options</a>
      <ul>
        <li> <a href="three-columns-layout.html">Three columns</a> </li>
        <li> <a href="two-column-layout.html">Two columns</a> </li>
        <li> <a href="three-column-small-layout.html">One big, two small</a> </li>
      </ul>
    </li>
    <li> <a href="#">Available components</a>
      <ul>
        <li> <a href="accordion.html">Accordion</a> </li>
        <li> <a href="tabs.html">Tabs</a> </li>
        <li> <a href="overlays.html">Overlays</a> </li>
      </ul>
    </li>
  </ul>
</div>
<div id="page-wrapper">
  <div id="main-wrapper">
    <div id="main-content">
      <div class="title title-spacing">
        <h2>Overlays</h2>
        Lorem ipsum dolor sic amet. </div>
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
  </div>
  <div id="sidebar">
    <div class="side-col ui-sortable">
      <div class="portlet ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
        <div class="portlet-header ui-widget-header">Theme Switcher</div>
        <div class="portlet-content">
          <ul class="side-menu">
            <li> <a class="set_theme" id="default" href="javascript:void(0);" style="font-weight:bold;" title="Default Theme">Default Theme</a> </li>
            <li> <a class="set_theme" id="light_blue" href="javascript:void(0);" title="Light Blue Theme">Light Blue Theme</a> </li>
          </ul>
        </div>
      </div>
      <div class="portlet ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
        <div class="portlet-header ui-widget-header">Layout Options</div>
        <div class="portlet-content">
          <ul class="side-menu">
            <li> Here, you can set the page width, either fixed or fluid. You decide!<br />
              <br />
            </li>
            <li id="fluid_layout"> <a href="javascript:void(0);" title="Fluid Layout">Switch to <b>Fluid Layout</b></a> </li>
            <li id="fixed_layout"> <a href="javascript:void(0);" title="Fixed Layout">Switch to <b>Fixed Layout</b></a> </li>
          </ul>
        </div>
      </div>
      <div class="portlet ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
        <div class="portlet-header ui-widget-header">Navigation Menu</div>
        <div class="portlet-content">
          <div id="accordion">
            <div>
              <h3><a href="#">Dashboard</a></h3>
              <div>
                <ul class="side-menu">
                  <li><a href="index.html" title="Administration">Administration</a></li>
                  <li><a href="forms.html" title="Forms">Forms Example</a></li>
                  <li><a href="tables.html" title="Tables">Tables example</a></li>
                </ul>
              </div>
            </div>
            <div>
              <h3><a href="#">Dummy drop down</a></h3>
              <div>
                <ul class="side-menu">
                  <li><a href="index.html" title="Administration">Administration</a></li>
                  <li><a href="forms.html" title="Forms">Forms Example</a></li>
                  <li><a href="tables.html" title="Tables">Tables example</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="other-box yellow-box ui-corner-all">
        <div class="cont tooltip ui-corner-all" title="Tooltips, tooltips, tooltips !">
          <h3>Tooltip !</h3>
          <p>This is a sample tooltip !</p>
        </div>
      </div>
      <div class="portlet ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
        <div class="portlet-header ui-widget-header">Accordion</div>
        <div class="portlet-content">
          <div id="datepicker"></div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="clearfix"></div>
<div id="footer">
  <div id="menu"> <a href="#" title="Home">Home</a> <a href="#" title="Administration">Administration</a> <a href="#" title="Settings">Settings</a> <a href="#" title="Contact">Contact</a> </div>
  Copyright &copy; 2009 - Horia Simon (WebDesignChimera.com) </div>
</body>
</html>