<?php
echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
echo $this->doctype();
?>
<html>
<head>
<?php echo $this->headTitle()?>

<?php echo $this->headMeta()?>

<?php echo $this->headLink()?>

<?php echo $this->headStyle()?>

<?php echo $this->headScript()?>

<?php echo $this->inlineScript()?>

<base href="<?php echo App::baseUri()?>" />
</head>
<body>
    <?php echo $this->layout()->content ?>
</body>
</html>