<?php
echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
echo $this->doctype();

?>
<html>
<head>
<?php
echo $this->headTitle()?>
<?php

echo $this->headMeta()?>
<?php

echo $this->headLink()?>
<?php

echo $this->headStyle()?>
<?php

echo $this->headScript()?>
<?php

echo $this->inlineScript()?>
<base href="<?php
echo App::baseUri()?>" />
</head>
<body>
<div class="top_bg">
<div class="container_16">
<div class="grid_5">
<div class="colortheme"></div>
<a href="default.htm"><img src="<?php
echo $this->tplIMG?>logo.png"
	class="logo" alt="Memix" /></a></div>

<div class="grid_11 menu"><!-- Top menu Start --> <?php
echo $this->partial('top_menu.phtml', array('navigation' => $this->navigation()->menu()))?>
<!-- Top menu End --></div>
</div>
</div>
<div class="clear">&nbsp;</div>
<?php
echo $this->partial('homepage_mainheader.phtml')?>
<div class="clear">&nbsp;</div>
<div class="container_16"><!-- 4 Blocks -->
<div class="grid_4 fbox"><img
	src="<?php
echo $this->tplIMG?>new_icon.png" alt="" class="leftalign" />
<h6><a href="@page_id=18">Web Designing</a></h6>
<p><small>Vestibulum blandit Sedeuism od enimeleifend inter.</small></p>
</div>
<div class="grid_4 fbox"><img
	src="<?php
echo $this->tplIMG?>menu_icon.png" alt="" class="leftalign" />
<h6><a href="#">Print & Graphics</a></h6>
<p><small>aoreetet congueeu osuere sit ametelit Sondimentum.</small></p>
</div>
<div class="grid_4 fbox"><img
	src="<?php
echo $this->tplIMG?>download_icon.png" alt=""
	class="leftalign" />
<h6><a href="#">Multimedia</a></h6>
<p><small>Loremipsum dolor sit amet, consectetur adipiscing elit.</small></p>
</div>
<div class="grid_4 fbox"><img
	src="<?php
echo $this->tplIMG?>copy_icon.png" alt="" class="leftalign" />
<h6><a href="#">SEO Marketing</a></h6>
<p><small>Nulla Fusce etlibero. Mauri smattis Duis vulpu acilisi cods.</small></p>
</div>
<!-- 4 Blocks --></div>
<div class="clear">&nbsp;</div>
<div class="content cbg">
<div class="container_16 linebg"><!--Left part of text follows here--> <?php
echo $this->partial('homepage_left_part_content.phtml', array('content' => $this->layout()->content))?>
<!--End of the Left part text  --> <!--Right part of text follows here-->
<?php
echo $this->partial('homepage_right_part.phtml', array('view' => $this))?>
<!--End of the Right part text  --></div>
</div>
</div>
<div class="clear">&nbsp;</div>
<!-- Footer Block Start -->
<?php
echo $this->partial('page_footer.phtml')?>
<!-- Footer Block End -->
</body>
</html>