<div class="side-box">
<h3>Sidebar Menu</h3>
<ul class="links">
	<li><a href="#">In the Woods</a></li>
</ul>
</div>


<div class="side-box">
<h3>What's New?</h3>
<ul>
	<li><a href="#">4 Traditional Japanese Styled Flash Websites</a><br>
	Sometimes flash is a good tool to use to design your website. You can
	give your visitors the feeling that you can't give using xhtml+css.
	Here are some of the cool websites I found that gave a taste of how
	Japanese tradition is. Oh, don't forget to have your volume low.</li>
</ul>
<input name="more" id="more" class="button" value="Read More"
	type="submit"></div>
<div class="side-box">
<h3>5 Top FAQ</h3>
<ul>
	<li><strong>Mauris mauris enim?</strong><br>
	Vestibulum fermentum malesuada quam eu luctus.</li>
</ul>
</div>