<div class="grid_5">
<div class="text">
<h2>Sub Menu</h2>
<ul class="submenu">
	<ul class="post-categories">
		<li><a href="@cat=5" title="View all posts in Category1"
			rel="category">Category1</a></li>
		<li><a href="@cat=6" title="View all posts in Category2"
			rel="category">Category2</a></li>
		<li><a href="@cat=7" title="View all posts in Category3"
			rel="category">Category3</a></li>
	</ul>
</ul>
</div>
<div class="text">
<ul class="submenu">
	<h2>Categories</h2>
	<ul>
		<li class="cat-item cat-item-4 current-cat"><a href="@cat=4"
			title="Blog">Blog</a></li>
		<li class="cat-item cat-item-5"><a href="@cat=5" title="Category1">Category1</a>
		</li>
		<li class="cat-item cat-item-6"><a href="@cat=6" title="Category2">Category2</a>
		</li>
		<li class="cat-item cat-item-7"><a href="@cat=7" title="Category3">Category3</a>
		</li>
		<li class="cat-item cat-item-8"><a href="@cat=8"
			title="Featured Products">Featured Products</a></li>
		<li class="cat-item cat-item-3"><a href="@cat=3" title="Portfolio1">Portfolio</a>
		</li>
		<li class="cat-item cat-item-1"><a href="@cat=1"
			title="View all posts filed under Uncategorized">Uncategorized</a></li>
	</ul>
</ul>
<br />
<h2 class="testimonialimg">Testimonials</h2>
<div class="testimonial">
<blockquote>
<p>Maecenas auctor, orci dignissim sodales adipiscing, lectus orci
ultricies mi, ac varius mauris enim at magna. Curabitur pretium sodales
eros, vitae ornare magna commodo quis. Maecenas eget tincidunt nulla<br />
<br />
Maecenas<br />
<a href="../../aivah.com/default.htm">Maecenas</a><br />

</blockquote>
</div>
</div>
<!--End of the Right part text  --></div>