<?php
echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
echo $this->doctype();

?>
<html>
<head>
<?php
echo $this->headTitle()?>
<?php echo $this->headMeta()?>

<?php echo $this->headLink()?>

<?php echo $this->headStyle()?>

<?php echo $this->headScript()?>

<script type="text/javascript"
	src="<?php echo App::baseUri()?>static/system/clientscripts/custom.js"></script>
<!--[if IE 6]>
	<link href="<?php echo App::baseUri()?>static/system/backoffice/css/ie6.css" rel="stylesheet" media="all" />
	<![endif]-->
<!--[if IE 7]>
	<link href="<?php echo App::baseUri()?>static/system/backoffice/css/ie7.css" rel="stylesheet" media="all" />
	<![endif]-->
<?php echo $this->inlineScript()?>
</head>
<body>
<div id="header">
<div id="top-menu"><a
	href="<?php	echo $this->url(array('module' => 'main', 'controller' => 'index', 'action' => 'index'))?>"><?php echo __('Go to homepage')?></a>
| <a
	href="<?php	echo $this->url(array('module' => 'main', 'controller' => 'profile', 'action' => 'settings'))?>"><?php echo __('Settings')?></a>
| <span><?php echo __('Logged in as')?> <a
	href="<?php	echo $this->url(array('profile_id' => $this->member->getId()), 'view_profile')?>"><?php echo $this->member->getField('first_name') . ' ' . $this->member->getField('last_name')?></a></span>
| <a
	href="<?php	echo $this->url(array('profile_id' => $this->member->getId()), 'view_profile')?>"><?php echo __('Profile')?></a>
| <a
	href="<?php	echo $this->url(array('module' => 'main', 'controller' => 'profile', 'action' => 'logout'))?>"><?php echo __('Log Out')?></a>

</div>
<div id="sitename"><a href="index.html" class="logo float-left"
	title="<?php echo $this->projectTitle?>"><?php echo $this->projectTitle?></a>
<div class="button float-right"><a href="#" id="dialog_link"
	class="btn ui-state-default ui-corner-all"><span
	class="ui-icon ui-icon-newwin"></span>Open Dialog</a> <a href="#"
	id="login_dialog" class="btn ui-state-default ui-corner-all"><span
	class="ui-icon ui-icon-image"></span>Open Login Box</a></div>
</div>
<?php echo $this->navigation()->menu($this->topMenu)->setUlClass('sf-navbar')?>
</div>
<div id="page-wrapper">
<div id="main-wrapper">
<div id="main-content">
<p><?php
$this->navigation()->breadcrumbs()->setSeparator(' > ');
echo $this->navigation()->breadcrumbs($this->topMenu)?></p>
<p><?php echo $this->messages()?></p>

<?php echo $this->layout()->content?>
<div class="clearfix"></div>
</div>
<div class="clearfix"></div>
</div>
<div id="sidebar">
<?php echo $this->render($this->sidebarBlocks)?>
<div class="clearfix"></div>
</div>
</div>
<div class="clearfix"></div>
<div id="footer">
<div id="menu"><?php echo $this->navigation()->menu($this->footerMenu)->setUlClass('footer_nav')?>
</div>
Copyright &copy; <?php echo date('Y')?> <?php echo $this->projectTitle?>
</div>
</body>
</html>
