<ul class="links">
<li>Operating system: <?php echo $this->os_version ?></li>
<li>PHP Version: <?php echo $this->php_version?> </li>
<li>PHP Server API: <?php echo $this->php_sapi?> </li>
<li>Zend Framework version: <?php echo $this->zf_version?> </li>
<li>Database adapter: <?php echo $this->sql_adapter?> </li>
<li>Database server version: <?php echo $this->sql_version?> </li>
<li>Image adapter component: <?php echo $this->image_adapter ?></li>
<li><?php echo $this->image_adapter ?> Version: <?php echo $this->image_adapter_version ?>
<li>Apache rewrite module: <?php echo ($this->apache_rewrite) ? __('available') : __('unvailable') ?></li>
<li>Free disk space: <?php echo $this->free_disk_space ?></li>
<li>Safe mode: <?php echo ($this->safe_mode) ? __('on') :  __('off') ?></li>
<li>Memory limit: <?php echo ($this->memory_limit) ? $this->memory_limit :  __('unvailable') ?></li>
<li>Disable functions: <?php echo ($this->disable_functions) ? $this->disable_functions :  __('unvailable') ?></li>
<li>Zlib extention: <?php echo ($this->zlib_ext) ? __('available') :  __('unvailable') ?></li>
<li>Iconv: <?php echo ($this->iconv_func) ? __('available') :  __('unvailable') ?></li>
</ul>