<div class="mainheader">
<div class="container_16"><!-- Slider Start-->
<div class="grid_8 featured">
<div id="mygallery" class="stepcarousel">
<div class="belt">
<div class="panel"><a href="@p=37"><img
	src="wp-content/themes/memex/timthumb.php@src=http_3A_2F_2Fwpdemo.bannersmonster.com_2Fmemex_2Fwp-content_2Fuploads_2F2009_2F05_2Fconspicuous.jpg&w=390&h=140"
	alt="Conspicuous variations of passages of Lorem Ipsum"
	class="borderimg" /></a></div>
<div class="panel"><a href="@p=36"><img
	src="wp-content/themes/memex/timthumb.php@src=http_3A_2F_2Fwpdemo.bannersmonster.com_2Fmemex_2Fwp-content_2Fuploads_2F2009_2F05_2Fplanetfull.jpg&w=390&h=140"
	alt="Planetfull the majority have suffered" class="borderimg" /></a></div>
<div class="panel"><a href="@p=34"><img
	src="wp-content/themes/memex/timthumb.php@src=http_3A_2F_2Fwpdemo.bannersmonster.com_2Fmemex_2Fwp-content_2Fuploads_2F2009_2F05_2Fvisionfull.jpg&w=390&h=140"
	alt="Vision Business Template" class="borderimg" /></a></div>
</div>
</div>
<!-- Slider End -->
<p class="textleft"><b>What are special offers?</b><br />
This is the place for your special offers or sign-up section for the
users or some campaign monitoring.</p>
</div>
<div class="grid_8 homeinfo">
<h1>We build <span>creative</span> web Designs!</h1>
<p class="textright">Here you can place some content related to your
specializations or some highlighting features of your product or so.</p>
<a href="#" class="tourbutton tb10 rightalign" /></a></div>
</div>
</div>