<script type="text/javascript">
 $(document).ready(function(){
    $('#redirect_to_backend').click(function(){ window.location = '<?php echo App::baseUri()?><?php echo App::config()->backoffice_path?>/'; });
    $('#redirect_to_frontend').click(function(){ window.location = '<?php echo App::baseUri()?>'; });
    
    $("#form_redirect").submit(function() {
      return false;
    });
 });
</script>

<?php echo $this->form ?>