<h2>System Requirements</h2>
<p><big>PHP:</big> v<?php echo $this->sysInfo->getRequiredPhpVersion()?>
or better</p>
<p><big>SQL:</big> MySQL v<?php echo $this->sysInfo->getRequiredMySQLVersion()?>
(5.0.0 or better preferred) with InnoDB engine</p>
<p>Your PHP version: <?php if (version_compare(PHP_VERSION, $this->sysInfo->getRequiredPhpVersion()) < 0) { ?>
<span style="color: red"><?php echo PHP_VERSION?> (this version of PHP
is not compatible with Engine, upgrade it to <?php echo $this->sysInfo->getRequiredPhpVersion()?>)</span>
<?php } else { ?> <span style="color: green"><?php echo PHP_VERSION?></span>
<?php }?></p>
<h2>PHP Extensions</h2>
<?php
foreach($this->check_php_extensions as $ext):
?>
<p><?php echo $ext['fancy_name']?>: <?php if(!$ext['hault']){?> <span
<?php if($ext['status']): ?> style="color: green">passed<?php else: ?>style="color:
red">recommended to install (<a href="<?php echo $ext['ext_web_url']?>">click
for more info</a>)<?php endif; ?></span> <?php }else {?> <span
<?php if($ext['status']): ?> style="color: green">passed<?php else: ?>style="color:
red">must be installed (<a href="<?php echo $ext['ext_web_url']?>">click
for more info</a>)<?php endif; ?></span> <?php } ?></p>
<?php
endforeach;
?>

<h2>Filesystem</h2>
<?php
foreach($this->check_filesystem as $dir):
?>
<p>Dir <?php echo trim(str_replace(str_replace('\\', '/', DOC_ROOT), '', $dir['path']), '/')?>:
<span <?php if($dir['is_writable']): ?> style="color: green">writable<?php else: ?>style="color:
red">not writable<?php endif; ?></span></p>
<?php
endforeach;
?>

<?php echo $this->form?>
