<?php
echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
echo $this->doctype();

?>
<html>
<head>
<?php
echo $this->headTitle()?>

<?php
echo $this->headMeta()?>

<?php
echo $this->headLink()?>

<?php
echo $this->headStyle()?>

<?php
echo $this->headScript()?>

<?php
echo $this->inlineScript()?>

<base href="<?php
echo App::baseUri()?>" />
</head>
<body>
<div id="main_container">
<div id="header">
<div id="logo"></div>
<div class="banner_adds"></div>
<div class="menu">
<ul>
	<li><a href="index.html">Home</a></li>
	<li><a href="admin.html">Admin <!--[if IE 7]><!--></a><!--<![endif]-->
	<!--[if lte IE 6]><table><tr><td><![endif]-->
	<ul>
		<li><a href="" title="">Lorem ipsum dolor sit amet</a></li>
	</ul>
	<!--[if lte IE 6]></td></tr></table></a><![endif]--></li>
	<li><a href="login.html">Login <!--[if IE 7]><!--></a><!--<![endif]-->
	<!--[if lte IE 6]><table><tr><td><![endif]-->
	<ul>
		<li><a href="" title="">Lorem ipsum dolor sit amet</a></li>
	</ul>
	<!--[if lte IE 6]></td></tr></table></a><![endif]--></li>
	<li><a href="list.html">Renting Homes <!--[if IE 7]><!--></a><!--<![endif]-->
	<!--[if lte IE 6]><table><tr><td><![endif]-->
	<ul>
		<li><a href="" title="">Lorem ipsum dolor sit amet</a></li>
		<li><a href="" title="">Lorem ipsum dolor sit amet</a></li>
	</ul>
	<!--[if lte IE 6]></td></tr></table></a><![endif]--></li>
	<li><a href="">About Us </a></li>
	<li><a href="">Customers</a></li>
	<li><a href="">FAQ</a></li>
	<li><a href="contact.html">Contact</a></li>
</ul>
</div>
</div>
<div id="main_content"><?php
echo $this->layout()->content?></div>
<!-- end of main_content -->
<div id="footer">
<div id="copyright">
<div style="float: left; padding: 3px;"></div>
<div style="float: left; padding: 14px 10px 10px 10px;">Company
name.&copy; All Rights Reserved 2008 - By <a href="http://csscreme.com"
	style="color: #772c17;">csscreme</a></div>
</div>
<ul class="footer_menu">
	<li><a href="index.html" class="nav_footer"> Home </a></li>
	<li><a href="#" class="nav_footer"> Selling Homes </a></li>
	<li><a href="" class="nav_footer"> Buying Homes </a></li>
	<li><a href="" class="nav_footer"> Renting Homes</a></li>
	<li><a href="" class="nav_footer"> RSS </a></li>
	<li><a href="" class="nav_footer"> Contact </a></li>
</ul>
</div>
</div>
<!-- end of main_container -->
</body>
</html>
