<?php
echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
echo $this->doctype();
?>
<html>
<head>
<?php echo $this->headTitle()?>

<?php echo $this->headMeta()?>

<?php echo $this->headLink()?>

<?php echo $this->headStyle()?>

<?php echo $this->headScript()?>

<?php echo $this->inlineScript()?>

<base href="<?php echo App::baseUri()?>" />
</head>
<body>
<div class="container_16">
  <div class="grid_16">
    <h1 id="branding">Engine Install</h1>
  </div>
  <div class="clear"></div>
  <div class="grid_4">&nbsp;</div>
  <div class="grid_12">
        <?php echo $this->layout()->content ?>
   </div>
  <div class="clear"></div>
</div>
</body>
</html>